### PR TITLE
add support for the <get-data> command from RFC 8526

### PR DESCRIPTION
**Pull request by kwatsen**
Add support for the `<get-data>` command from [RFC 8526](https://datatracker.ietf.org/doc/rfc8526).
Tested (partially) against live NETCONF servers.

Please disregard PR https://github.com/ADTRAN/netconf_client/pull/33.

### CODE REVIEW

**Comment by kwatsen** [comment]
Hi there!

Can you Approve and run the workflow for my PR?

Thanks,
Kent

**Comment by kwatsen** [comment]
I ran `poetry run black .` to fix the CI issue.

It looks like the workflow-run needs to be approved again.

Thank you.

**Comment by kwatsen** [comment]
Sorry to decrease the Coverage by 0.5% 🙇  
Still, 83% is very good!

I think the PR is all set now...
Are you okay with reviewing it?
Hoping to get it merged today 🤞 

Thanks again,
Kent

**Review by JennToo — APPROVED** [review]

**Comment by wburkhardt** [comment]
Hi kwatsen,
I noticed your commits - thank you very much for your contribution.
Please give me a bit more time to review and approve/merge (one or two days), I'm a bit busy at the moment. Thank you!

**Comment by wburkhardt** [comment]
Ah, thanks JennToo. You have been faster than me. 👍

**Comment by JennToo** [comment]
No worries @wburkhardt ! I had a few free minutes

Thanks for the contribution @kwatsen ! The changes have been released in 2.5.0

**Pull request merged**
